# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MUSE <- function(data_mean_gamma, data_s2_gamma, data_mean_Gamma, data_s2_Gamma, n_snps, iter_times = 1000L, R_SNP = NULL) {
    .Call(`_MUSE_MUSE`, data_mean_gamma, data_s2_gamma, data_mean_Gamma, data_s2_Gamma, n_snps, iter_times, R_SNP)
}

rnorm_cpp <- function(n, mean, sd) {
    .Call(`_MUSE_rnorm_cpp`, n, mean, sd)
}

dnorm_cpp <- function(x, mean, sd) {
    .Call(`_MUSE_dnorm_cpp`, x, mean, sd)
}

mvrnorm_cpp <- function(n, mean, cov_matrix) {
    .Call(`_MUSE_mvrnorm_cpp`, n, mean, cov_matrix)
}

runi_cpp <- function(min_val, max_val) {
    .Call(`_MUSE_runi_cpp`, min_val, max_val)
}

rinvgamma_cpp <- function(n, shape, scale) {
    .Call(`_MUSE_rinvgamma_cpp`, n, shape, scale)
}

rsample <- function(characters, probs, sample_size) {
    .Call(`_MUSE_rsample`, characters, probs, sample_size)
}

rDirichlet <- function(alpha, times) {
    .Call(`_MUSE_rDirichlet`, alpha, times)
}

lm_cpp <- function(y, X) {
    .Call(`_MUSE_lm_cpp`, y, X)
}

cor_cpp <- function(input_matrix) {
    .Call(`_MUSE_cor_cpp`, input_matrix)
}

whichIn <- function(x, values) {
    .Call(`_MUSE_whichIn`, x, values)
}

vtv <- function(x, y) {
    .Call(`_MUSE_vtv`, x, y)
}

qt_cpp <- function(x, probs) {
    .Call(`_MUSE_qt_cpp`, x, probs)
}

res_output <- function(x) {
    .Call(`_MUSE_res_output`, x)
}

index_cpp <- function(x, index) {
    .Call(`_MUSE_index_cpp`, x, index)
}

minor_genotype <- function(x) {
    .Call(`_MUSE_minor_genotype`, x)
}

genotype_generation <- function(size_sample) {
    .Call(`_MUSE_genotype_generation`, size_sample)
}

order_abs <- function(x, decreasing) {
    .Call(`_MUSE_order_abs`, x, decreasing)
}

rmindex <- function(x, indices) {
    .Call(`_MUSE_rmindex`, x, indices)
}

arm_to_num <- function(x) {
    .Call(`_MUSE_arm_to_num`, x)
}

